### ISSUE TITLE
Server crash with void flower.

### ISSUE THREAD

**Issue by KELETU66666** [Jboymercs/bomd#1]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (BedBreakBegone-1.0.2.jar)
  FermiumBooter (`FermiumBooter-1.1.1.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.10.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.6.0.jar)
  PhosphorFMLPlugin (phosphor-1.12.2-0.2.9.3-SNAPSHOT.jar)
  EarlyMixinInit (NovaLogin-forge-1.12.2-0.2.2.jar)
  LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  FutureMC (Future-MC-0.2.20.jar)
  Born in a Barn (Born In A Barn 1.8-1.12-1.2.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  Aqua Acrobatics Transformer (AquaAcrobatics-1.15.4.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  DupeFixProjectCoreMod (DupeFixProject-1.12.2-3.1.6.jar)
  MixinBooter (!mixinbooter-9.4.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
  RLTweaker ASM (RLTweaker-1.12.2-0.6.5.jar)
  OECore (OceanicExpanse-1.1.4.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  EnigmaticLegacyCore (enigmaticlegacy-0.10.1-r-f.jar)
  ConfigAnytimePlugin (!configanytime-3.0.jar)
  StellarCoreEarlyMixinLoader (StellarCore-1.5.4.jar)
  Bundles (Bundles-1.21.jar)
  MixinLoader (framevoidpatch-1.0.0.jar)
  BetterCombat (RLCombat-1.12.2-2.2.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 24-11-19 下午10:50
Description: Ticking entity

java.lang.NoSuchMethodError: com.dungeon_additions.da.entity.blossom.ProjectileSporeBomb.func_70016_h(DDD)V
	at com.dungeon_additions.da.entity.blossom.EntityVoidBlossom.lambda$null$19(EntityVoidBlossom.java:262)
	at com.dungeon_additions.da.entity.EntityAbstractBase.func_70636_d(EntityAbstractBase.java:196)
	at com.dungeon_additions.da.entity.blossom.EntityAbstractVoidBlossom.func_70636_d(EntityAbstractVoidBlossom.java:233)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.dungeon_additions.da.entity.EntityAbstractBase.func_70071_h_(EntityAbstractBase.java:119)
	at com.dungeon_additions.da.entity.blossom.EntityAbstractVoidBlossom.func_70071_h_(EntityAbstractVoidBlossom.java:108)
	at com.dungeon_additions.da.entity.blossom.EntityVoidBlossom.func_70071_h_(EntityVoidBlossom.java:151)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

No Mixin Metadata is found in the Stacktrace.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.dungeon_additions.da.entity.blossom.EntityVoidBlossom.lambda$null$19(EntityVoidBlossom.java:262)
	at com.dungeon_additions.da.entity.EntityAbstractBase.func_70636_d(EntityAbstractBase.java:196)
	at com.dungeon_additions.da.entity.blossom.EntityAbstractVoidBlossom.func_70636_d(EntityAbstractVoidBlossom.java:233)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.dungeon_additions.da.entity.EntityAbstractBase.func_70071_h_(EntityAbstractBase.java:119)
	at com.dungeon_additions.da.entity.blossom.EntityAbstractVoidBlossom.func_70071_h_(EntityAbstractVoidBlossom.java:108)
	at com.dungeon_additions.da.entity.blossom.EntityVoidBlossom.func_70071_h_(EntityVoidBlossom.java:151)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: da:void_blossom (com.dungeon_additions.da.entity.blossom.EntityVoidBlossom)
	Entity ID: 130268
	Entity Name: Void Blossom
	Entity's Exact location: 482.50, 14.00, -2797.50
	Entity's Block location: World: (482,14,-2798), Chunk: (at 2,0,2 in 30,-175; contains blocks 480,0,-2800 to 495,255,-2785), Region: (0,-6; contains chunks 0,-192 to 31,-161, blocks 0,0,-3072 to 511,255,-2561)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 5 total; [EntityPlayerMP['keletu'/80425, l='world', x=475.25, y=19.32, z=-2804.96], EntityPlayerMP['SHYG1997'/2493, l='world', x=-1239.71, y=31.00, z=-306.65], EntityPlayerMP['wenhao'/4429, l='world', x=-1303.70, y=72.00, z=-445.35], EntityPlayerMP['inkroe'/29970, l='world', x=266.29, y=75.75, z=656.09], EntityPlayerMP['Tiant'/2368, l='world', x=494.61, y=15.31, z=-2799.47]]
	Chunk stats: ServerChunkCache: 916 Drop: 0
	Level seed: -267029568337511623
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (809,75,789), Chunk: (at 9,4,5 in 50,49; contains blocks 800,0,784 to 815,255,799), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 2276263 game time, 2276263 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 12571 (now: true), thunder time: 8533 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_421, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6232746344 bytes (5944 MB) / 8589934592 bytes (8192 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 16 total; -Xmx16G -Xms8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 80 mods loaded, 80 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version          | Source                                     | Signature                                |
	|:------ |:-------------------- |:---------------- |:------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2           | minecraft.jar                              | None                                     |
	| LCHIJA | mcp                  | 9.42             | minecraft.jar                              | None                                     |
	| LCHIJA | FML                  | 8.0.99.99        | forge-1.12.2-14.23.5.2859.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2859     | forge-1.12.2-14.23.5.2859.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | mixinbooter          | 9.4              | minecraft.jar                              | None                                     |
	| LCHIJA | foamfixcore          | 7.7.4            | minecraft.jar                              | None                                     |
	| LCHIJA | randompatches        | 1.12.2-1.22.1.10 | randompatches-1.12.2-1.22.1.10.jar         | None                                     |
	| LCHIJA | configanytime        | 3.0              | !configanytime-3.0.jar                     | None                                     |
	| LCHIJA | fermiumbooter        | 1.1.1            | `FermiumBooter-1.1.1.jar                   | None                                     |
	| LCHIJA | advanced-fishing     | 1.3.3            | Advanced-Fishing-1.12.2-1.3.3.jar          | None                                     |
	| LCHIJA | aireducer            | 0.3.0            | AIReducer-1.12.2-0.3.0.jar                 | None                                     |
	| LCHIJA | crafttweaker         | 4.1.20           | CraftTweaker2-1.12-4.1.20.699.jar          | None                                     |
	| LCHIJA | jei                  | 4.16.1.1013      | jei_1.12.2-4.16.1.1013.jar                 | None                                     |
	| LCHIJA | appleskin            | 1.0.14           | AppleSkin-mc1.12-1.0.14.jar                | None                                     |
	| LCHIJA | aquaacrobatics       | 1.15.4           | AquaAcrobatics-1.15.4.jar                  | None                                     |
	| LCHIJA | aquaculture          | 1.6.8            | Aquaculture-1.12.2-1.6.8.jar               | None                                     |
	| LCHIJA | atlaslib             | 1.1.5a           | Atlas-Lib-1.12.2-1.1.5a.jar                | None                                     |
	| LCHIJA | attributefix         | 1.0.12           | AttributeFix-Forge-1.12.2-1.0.12.jar       | None                                     |
	| LCHIJA | baubles              | 1.5.2            | Baubles-1.12-1.5.2.jar                     | None                                     |
	| LCHIJA | bedbreakbegone       | 1.0.2            | BedBreakBegone-1.0.2.jar                   | None                                     |
	| LCHIJA | bountifulbaubles     | 0.0.1            | Bountiful Baubles-1.12.2-0.1.8.jar         | None                                     |
	| LCHIJA | bundles              | 1.21             | Bundles-1.21.jar                           | None                                     |
	| LCHIJA | reskillable          | 1.12.2-1.13.0    | Reskillable-1.12.2-1.13.0.jar              | None                                     |
	| LCHIJA | compatskills         | 1.12.2-1.17.0    | CompatSkills-1.12.2-1.17.0.jar             | None                                     |
	| LCHIJA | crafttweakerjei      | 2.0.3            | CraftTweaker2-1.12-4.1.20.699.jar          | None                                     |
	| LCHIJA | da                   | 0.0.7            | da-1.12.2-0.0.7.jar                        | None                                     |
	| LCHIJA | debark               | 0.1.3            | Debark-0.1.3.jar                           | None                                     |
	| LCHIJA | deeperdepths         | 1.0.2            | Deeper-Depths-1.12.2-1.0.2.jar             | None                                     |
	| LCHIJA | dupefixproject       | 3.1.6            | DupeFixProject-1.12.2-3.1.6.jar            | None                                     |
	| LCHIJA | dynaores             | 1.0.3a           | Dynamic-Raw-Ores-1.12.2-1.0.3a.jar         | None                                     |
	| LCHIJA | orelib               | 3.6.0.1          | OreLib-1.12.2-3.6.0.1.jar                  | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround            | @VERSION@        | DynamicSurroundings-1.12.2-3.6.3.jar       | None                                     |
	| LCHIJA | patchouli            | 1.0-23.6         | Patchouli-1.0-23.6.jar                     | None                                     |
	| LCHIJA | enigmaticlegacy      | 0.10.0           | enigmaticlegacy-0.10.1-r-f.jar             | None                                     |
	| LCHIJA | mod_lavacow          | 1.5.0            | Fish's Undead Rising-1.4.2.jar             | None                                     |
	| LCHIJA | fishingmadebetter    | 2.2.6            | FishingMadeBetter-1.12.2-2.2.6.jar         | None                                     |
	| LCHIJA | cursedlib            | 1.0.0            | FlameLib-1.12.2-0.0.7.jar                  | None                                     |
	| LCHIJA | foamfix              | @VERSION@        | foamfix-0.10.15-1.12.2.jar                 | None                                     |
	| LCHIJA | forgeessentials      | 12               | forgeessentials-1.12.2-12.4.126-server.jar | None                                     |
	| LCHIJA | forgelin             | 1.8.4            | Forgelin-1.8.4.jar                         | None                                     |
	| LCHIJA | llibrary             | 1.7.20           | llibrary-1.7.20-1.12.2.jar                 | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil               | 8.0.5            | fossilsarcheology-8.0.6.jar                | None                                     |
	| LCHIJA | framevoidpatch       | 1.0.0            | framevoidpatch-1.0.0.jar                   | None                                     |
	| LCHIJA | futuremc             | 0.2.6            | Future-MC-0.2.20.jar                       | None                                     |
	| LCHIJA | geckolib3            | 3.0.30           | geckolib-forge-1.12.2-3.0.31.jar           | None                                     |
	| LCHIJA | gravestone           | 1.10.3           | gravestone-1.10.3.jar                      | None                                     |
	| LCHIJA | growthcraft_hops     | 4.3.0            | growthcraft-1.12.2-4.3.0.jar               | None                                     |
	| LCHIJA | growthcraft          | 4.3.0            | growthcraft-1.12.2-4.3.0.jar               | None                                     |
	| LCHIJA | growthcraft_fishtrap | 4.3.0            | growthcraft-1.12.2-4.3.0.jar               | None                                     |
	| LCHIJA | growthcraft_cellar   | 4.3.0            | growthcraft-1.12.2-4.3.0.jar               | None                                     |
	| LCHIJA | growthcraft_bees     | 4.3.0            | growthcraft-1.12.2-4.3.0.jar               | None                                     |
	| LCHIJA | growthcraft_milk     | 4.3.0            | growthcraft-1.12.2-4.3.0.jar               | None                                     |
	| LCHIJA | growthcraft_bamboo   | 4.3.0            | growthcraft-1.12.2-4.3.0.jar               | None                                     |
	| LCHIJA | growthcraft_apples   | 4.3.0            | growthcraft-1.12.2-4.3.0.jar               | None                                     |
	| LCHIJA | growthcraft_grapes   | 4.3.0            | growthcraft-1.12.2-4.3.0.jar               | None                                     |
	| LCHIJA | growthcraft_rice     | 4.3.0            | growthcraft-1.12.2-4.3.0.jar               | None                                     |
	| LCHIJA | waila                | 1.8.26           | Hwyla-1.8.26-B41_1.12.2.jar                | None                                     |
	| LCHIJA | iceandfire           | 1.9.1-2.0.0      | Ice and Fire-2.0.0.jar                     | None                                     |
	| LCHIJA | improvedbackpacks    | 1.12.2-1.5.0.0   | ImprovedBackpacks-1.12.2-1.5.0.0.jar       | None                                     |
	| LCHIJA | mobends              | 1.2.1            | MoBends_1.12.2-1.2.1-19.12.21.jar          | None                                     |
	| LCHIJA | nanhealthfixer       | 1.12.2-0.0.1     | nanhealthfixer-1.12.2-0.0.1.jar            | None                                     |
	| LCHIJA | novalogin            | 0.2.2            | NovaLogin-forge-1.12.2-0.2.2.jar           | None                                     |
	| LCHIJA | oe                   | 1.1.4            | OceanicExpanse-1.1.4.jar                   | None                                     |
	| LCHIJA | portaldupebegone     | 1.0.0            | PortalDupeBegone-1.0.0.jar                 | None                                     |
	| LCHIJA | raids                | 1.1.4            | Raids-Backport-1.12.2-1.1.4.jar            | None                                     |
	| LCHIJA | reachfix             | 1.0.10           | ReachFix-1.12.2-1.0.10.jar                 | None                                     |
	| LCHIJA | artifacts            | 1.1.2            | RLArtifacts-1.1.2.jar                      | None                                     |
	| LCHIJA | bettercombatmod      | 2.2.2            | RLCombat-1.12.2-2.2.2.jar                  | None                                     |
	| LCHIJA | rltweaker            | 0.6.5            | RLTweaker-1.12.2-0.6.5.jar                 | None                                     |
	| LCHIJA | xat                  | 0.32.5           | Trinkets and Baubles-0.32.5.jar            | None                                     |
	| LCHIJA | spartanweaponry      | 1.6.0            | SpartanWeaponry-1.12.2-1.6.0.jar           | None                                     |
	| LCHIJA | spartanfire          | 0.4              | spartanlightning-0.4.jar                   | None                                     |
	| LCHIJA | spawnercontrol       | 1.6.3b           | SpawnerControl-1.6.3b.jar                  | None                                     |
	| LCHIJA | stellar_core         | 1.5.4            | StellarCore-1.5.4.jar                      | None                                     |
	| LCHIJA | surge                | 2.0.79           | Surge-1.12.2-2.0.79.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | villagenames         | 4.4.12           | VillageNames-1.12.2-4.4.12.jar             | None                                     |
	| LCHIJA | waystones            | 4.1.0            | Waystones_1.12.2-4.1.0.jar                 | None                                     |
	| LCHIJA | claimitapi           | 1.12.2-1.2.1     | claimitapi-1.12.2-1.2.1.jar                | None                                     |
	| LCHIJA | claimit              | 1.12.2-1.2.1     | claimit-1.12.2-1.2.1.jar                   | None                                     |
	| LCHIJA | phosphor-lighting    | 1.12.2-0.2.9.3   | phosphor-1.12.2-0.2.9.3-SNAPSHOT.jar       | None                                     |

	Loaded coremods (and transformers): 
MixinLoader (BedBreakBegone-1.0.2.jar)
  
FermiumBooter (`FermiumBooter-1.1.1.jar)
  
ReachFixPlugin (ReachFix-1.12.2-1.0.10.jar)
  meldexun.reachfix.asm.ReachFixClassTransformer
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.6.0.jar)
  
PhosphorFMLPlugin (phosphor-1.12.2-0.2.9.3-SNAPSHOT.jar)
  
EarlyMixinInit (NovaLogin-forge-1.12.2-0.2.2.jar)
  
LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
FutureMC (Future-MC-0.2.20.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
Born in a Barn (Born In A Barn 1.8-1.12-1.2.jar)
  com.chocohead.biab.BornInABarn
RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  com.therandomlabs.randompatches.core.RPTransformer
Aqua Acrobatics Transformer (AquaAcrobatics-1.15.4.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
DupeFixProjectCoreMod (DupeFixProject-1.12.2-3.1.6.jar)
  
MixinBooter (!mixinbooter-9.4.jar)
  
TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
  
SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
  
RLTweaker ASM (RLTweaker-1.12.2-0.6.5.jar)
  com.charles445.rltweaker.asm.RLTweakerASM
OECore (OceanicExpanse-1.1.4.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
EnigmaticLegacyCore (enigmaticlegacy-0.10.1-r-f.jar)
  
ConfigAnytimePlugin (!configanytime-3.0.jar)
  
StellarCoreEarlyMixinLoader (StellarCore-1.5.4.jar)
  
Bundles (Bundles-1.21.jar)
  
MixinLoader (framevoidpatch-1.0.0.jar)
  
BetterCombat (RLCombat-1.12.2-2.2.2.jar)
  
	ForgeEssentials: Running ForgeEssentials 12.4.126 (5def12e). Modules loaded: Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WorldBorder
	RLTweaker Error Report: 
 Motion Checker Knockback Same Position : 3
 
	Profiler Position: N/A (disabled)
	Player Count: 6 / 20; [EntityPlayerMP['keletu'/80425, l='world', x=475.25, y=19.32, z=-2804.96], EntityPlayerMP['SHYG1997'/2493, l='world', x=-1239.71, y=31.00, z=-306.65], EntityPlayerMP['pomato233'/127523, l='world', x=277.27, y=83.22, z=-1743.32], EntityPlayerMP['wenhao'/4429, l='world', x=-1303.70, y=72.00, z=-445.35], EntityPlayerMP['inkroe'/29970, l='world', x=266.29, y=75.75, z=656.09], EntityPlayerMP['Tiant'/2368, l='world', x=494.61, y=15.31, z=-2799.47]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Jboymercs** [comment]
Fixed via 0.7. Some weird geckolib stuff occurred, it is fixed now.
